name: Elixir

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      uses: jidicula/clang-format-action@v4.14.0
      with:
        check-path: 'src'
        clang-format-version: '18'
